import PassingYardsLeaders from "../../Assets/passing-yards-john.svg";

export const StatsPlayersLeaderList = [
  {
    cardtitle: "Passing Yards ",
    playerImage: PassingYardsLeaders,
    playerName: "Josh Allen, QB",
    playerNumber: "2,018",
  },
  {
    cardtitle: "Passing Yards ",
    playerImage: PassingYardsLeaders,
    playerName: "Josh Allen, QB",
    playerNumber: "2,018",
  },
  {
    cardtitle: "Passing Yards ",
    playerImage: PassingYardsLeaders,
    playerName: "Josh Allen, QB",
    playerNumber: "2,018",
  },
  {
    cardtitle: "Passing Yards ",
    playerImage: PassingYardsLeaders,
    playerName: "Josh Allen, QB",
    playerNumber: "2,018",
  },
  {
    cardtitle: "Passing Yards ",
    playerImage: PassingYardsLeaders,
    playerName: "Josh Allen, QB",
    playerNumber: "2,018",
  },
];

export const nflTableDetailStats = [
  {
    mainHeading: "Passing",
    subHeadings: [
      {
        subHeading1: "NAME",
        subHeading2: "GP",
        subHeading3: "CMP",
        subHeading4: "ATT",
        subHeading5: "CMP%",
        subHeading6: "YDS",
        subHeading7: "AVG",
        subHeading8: "YDS/G",
        subHeading9: "LNG",
        subHeading10: "TD",
        subHeading11: "INT",
        subHeading12: "SACK",
        subHeading13: "SYL",
        subHeading14: "RTG",
      },
    ],
    tableContent: [
      {
        name: "Josh Allen",
        name2: "QB",
        gp: "5",
        cmp: "5",
        att: "2",
        cmp1: "0",
        yds: ".714",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "12",
        syl: "82",
        rtg: "105.0",
      },
      {
        name: "Matt Barkley",
        name2: "QB",
        gp: "5",
        cmp: "5",
        att: "2",
        cmp1: "0",
        yds: ".500",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "+75",
        rtg: "W1",
      },
    ],
    tableTotalContent: [
      {
        name: "Total",
        gp: "7",
        cmp: "5",
        att: "4",
        cmp1: "0",
        yds: ".333",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "-28",
        rtg: "W1",
      },
    ],
  },

  {
    mainHeading: "Rushing",
    subHeadings: [
      {
        subHeading1: "NAME",
        subHeading2: "GP",
        subHeading3: "",
        subHeading4: "ATT",
        subHeading5: "",
        subHeading6: "YDS",
        subHeading7: "AVG",
        subHeading8: "LNG",
        subHeading9: "BIG",
        subHeading10: "TD",
        subHeading11: "YDS/G",
        subHeading12: "FUM",
        subHeading13: "LST",
        subHeading14: "FD",
      },
    ],
    tableContent: [
      {
        name: "Devin Singletary",
        name2: "RB",
        gp: "5",
        cmp: "",
        att: "2",
        cmp1: "",
        yds: ".714",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "12",
        syl: "82",
        rtg: "105.0",
      },
      {
        name: "Josh Allen",
        name2: "QB",
        gp: "5",
        cmp: "",
        att: "2",
        cmp1: "",
        yds: ".500",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "+75",
        rtg: "W1",
      },
      {
        name: "Zack Moss",
        name2: "RB",
        gp: "5",
        cmp: "",
        att: "2",
        cmp1: "",
        yds: ".500",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "+75",
        rtg: "W1",
      },
      {
        name: "T.J. Yeldon",
        name2: "RB",
        gp: "5",
        cmp: "",
        att: "2",
        cmp1: "",
        yds: ".500",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "+75",
        rtg: "W1",
      },
      {
        name: "Isaiah McKenzie WR",
        name2: "RB",
        gp: "5",
        cmp: "",
        att: "2",
        cmp1: "",
        yds: ".500",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "+75",
        rtg: "W1",
      },
      {
        name: "Gabriel Davis",
        name2: "WR",
        gp: "5",
        cmp: "",
        att: "2",
        cmp1: "",
        yds: ".500",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "+75",
        rtg: "W1",
      },
      {
        name: "Andre Roberts",
        name2: "WR",
        gp: "5",
        cmp: "",
        att: "2",
        cmp1: "",
        yds: ".500",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "+75",
        rtg: "W1",
      },
    ],
    tableTotalContent: [
      {
        name: "Total",
        gp: "7",
        cmp: "5",
        att: "4",
        cmp1: "0",
        yds: ".333",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "-28",
        rtg: "W1",
      },
    ],
  },

  {
    mainHeading: "Receiving",
    subHeadings: [
      {
        subHeading1: "NAME",
        subHeading2: "GP",
        subHeading3: "REC",
        subHeading4: "TGTS",
        subHeading5: "",
        subHeading6: "YDS",
        subHeading7: "AVG",
        subHeading8: "TD",
        subHeading9: "LNG",
        subHeading10: "BIG",
        subHeading11: "YDS/G",
        subHeading12: "FUM",
        subHeading13: "LST",
        subHeading14: "YAC",
        subHeading15: "FD",
      },
    ],
    tableContent: [
      {
        name: "Stefon Diggs",
        name2: "WR",
        gp: "5",
        cmp: "2",
        att: "2",
        cmp1: "",
        yds: ".714",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "12",
        syl: "82",
        rtg: "82",
        fd: "105.0",
      },
      {
        name: "Cole Beasley",
        name2: "WR",
        gp: "5",
        cmp: "2",
        att: "2",
        cmp1: "",
        yds: ".500",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "+75",
        rtg: "+75",
        fd: "W1",
      },
      {
        name: "John Brown",
        name2: "WR",
        gp: "5",
        cmp: "2",
        att: "2",
        cmp1: "",
        yds: ".500",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "+75",
        rtg: "+75",
        fd: "W1",
      },
      {
        name: "Gabriel Davis",
        name2: "RB",
        gp: "5",
        cmp: "2",
        att: "2",
        cmp1: "",
        yds: ".500",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "+75",
        rtg: "+75",
        fd: "W1",
      },
      {
        name: "Isaiah McKenzie",
        name2: "WR",
        gp: "5",
        cmp: "2",
        att: "2",
        cmp1: "",
        yds: ".500",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "+75",
        rtg: "+75",
        fd: "W1",
      },
      {
        name: "Gabriel Davis",
        name2: "WR",
        gp: "5",
        cmp: "2",
        att: "2",
        cmp1: "",
        yds: ".500",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "+75",
        rtg: "+75",
        fd: "W1",
      },
      {
        name: "Andre Roberts",
        name2: "WR",
        gp: "5",
        cmp: "2",
        att: "2",
        cmp1: "",
        yds: ".500",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "+75",
        rtg: "+75",
        fd: "W1",
      },
    ],
    tableTotalContent: [
      {
        name: "Total",
        gp: "7",
        cmp: "5",
        att: "4",
        cmp1: "0",
        yds: ".333",
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: "174",
        sack: "178",
        syl: "-28",
        rtg: "W1",
        fd: "W1",
      },
    ],
  },
];
