import tableImg1 from "../../Assets/nfl-table-1.png";
import tableImg2 from "../../Assets/nfl-table-2.png";
import tableImg3 from "../../Assets/nfl-table-3.png";
import tableImg4 from "../../Assets/nfl-table-4.png";
import tableImg5 from "../../Assets/nfl-table-5.png";
import tableImg6 from "../../Assets/nfl-table-6.png";
import tableImg7 from "../../Assets/nfl-table-7.png";
import tableImg8 from "../../Assets/nfl-table-8.png";
import tableImg9 from "../../Assets/nfl-table-9.png";
import tableImg10 from "../../Assets/nfl-table-10.png";
import tableImg11 from "../../Assets/nfl-table-11.png";
import tableImg12 from "../../Assets/nfl-table-12.png";
import tableImg13 from "../../Assets/nfl-table-13.png";
import tableImg14 from "../../Assets/nfl-table-14.png";
import tableImg15 from "../../Assets/nfl-table-15.png";
import tableImg16 from "../../Assets/nfl-table-16.png";
import tableImg17 from "../../Assets/nfl-table-17.png";
import { RightLightArrow } from "./Icons";

export const nflTeamStatsList = [
  {
    heading: "Regular Season",
    subHeading1: "WK",
    subHeading2: "DATE",
    subHeading3: "OPPONENT",
    subHeading4: "RESULT",
    subHeading5: "W-L",
    subHeading6: "HI PASS",
    subHeading7: "HI RUSH",
    subHeading8: "HI REC",
    tableContent: [
      {
        srNo: "1",
        dateTable: "Sun, 13 Sep",
        imgUrl: tableImg1,
        opponentGrey: "vs",
        opponentBlue: "New York",
        result: "27-17",
        greenRedText: "W",
        wL: "1-0",
        hiPassBlue: "Allen",
        hiPassGrey: "312",
        hiRushGrey: "57",
        hiRushBlue: "Allen",
        hiRecGrey: "86",
        hiRecBlue: "Diggs",
      },
      {
        srNo: "2",
        dateTable: "Sun, 20 Sep",
        imgUrl: tableImg7,
        opponentGrey: "@",
        opponentBlue: "Miami",
        result: "31-28",
        greenRedText: "W",
        wL: "2-0",
        hiPassBlue: "Allen",
        hiPassGrey: " 415",
        hiRushGrey: " 56",
        hiRushBlue: "Singletary",
        hiRecGrey: "153",
        hiRecBlue: "Diggs",
      },
      {
        srNo: "3",
        dateTable: "Sun, 27 Sep",
        imgUrl: tableImg8,
        opponentGrey: "vs",
        opponentBlue: "Los Angeles",
        result: "35-32",
        greenRedText: "W",
        wL: "3-0",
        hiPassBlue: "Allen",
        hiPassGrey: " 311",
        hiRushGrey: "71",
        hiRushBlue: "Singletary",
        hiRecGrey: "100",
        hiRecBlue: "Beasley",
      },
      {
        srNo: "4",
        dateTable: "Mon, 5 Oct",
        imgUrl: tableImg5,
        opponentGrey: "@",
        opponentBlue: "Las Vegas",
        result: "30-23",
        greenRedText: "W",
        wL: "4-0",
        hiPassBlue: "Allen",
        hiPassGrey: "288",
        hiRushGrey: " 56",
        hiRushBlue: "Singletary",
        hiRecGrey: "115",
        hiRecBlue: "Diggs",
      },
      {
        srNo: "5",
        dateTable: "Wed, 14 Oct",
        imgUrl: tableImg4,
        opponentGrey: "@",
        opponentBlue: "Tennessee",
        result: "42-16",
        greenRedText: "L",
        wL: "4-1",
        hiPassBlue: "Allen",
        hiPassGrey: "263",
        hiRushGrey: "42",
        hiRushBlue: "Yeldon",
        hiRecGrey: "106",
        hiRecBlue: "Diggs",
      },
      {
        srNo: "6",
        dateTable: "Tue, 20 Oct",
        imgUrl: tableImg6,
        opponentGrey: "vs",
        opponentBlue: "Kansas City",
        result: "26-17",
        greenRedText: "L",
        wL: "4-2",
        hiPassBlue: "Allen",
        hiPassGrey: "122",
        hiRushGrey: "42",
        hiRushBlue: "Allen",
        hiRecGrey: "46",
        hiRecBlue: "Diggs",
      },
      {
        srNo: "7",
        dateTable: "Sun, 25 Oct",
        imgUrl: tableImg1,
        opponentGrey: "@",
        opponentBlue: "New York",
        result: "18-10",
        greenRedText: "W",
        wL: "5-2",
        hiPassBlue: "Allen",
        hiPassGrey: "307",
        hiRushGrey: "61",
        hiRushBlue: "Allen",
        hiRecGrey: "112",
        hiRecBlue: "Beasley",
      },
      {
        srNo: "8",
        dateTable: "Sun, 1 Nov",
        imgUrl: tableImg2,
        opponentGrey: "vs",
        opponentBlue: "New England",
        result: "24-21",
        greenRedText: "W",
        wL: "6-2",
        hiPassBlue: "Allen",
        hiPassGrey: "154",
        hiRushGrey: "86",
        hiRushBlue: "Singletary",
        hiRecGrey: "92",
        hiRecBlue: "Diggs",
      },
    ],
  },
  {
    heading: "",
    subHeading1: "WK",
    subHeading2: "DATE",
    subHeading3: "OPPONENT",
    subHeading4: "TIME",
    subHeading5: "TV",
    subHeading6: "TICKETS",
    subHeading7: "",
    subHeading8: "",
    tableContent: [
      {
        srNo: "9",
        dateTable: "Sun, 8 Nov",
        opponentGrey: "vs",
        imgUrl: tableImg3,
        opponentBlue: "Seattle",
        result: "11:30 PM",
        greenRedText: "",
        wL: "",
        hiPassBlue: "Tickets as low as $40",
        hiPassGrey: <RightLightArrow />,
        hiRushGrey: "",
        hiRushBlue: "",
        hiRecGrey: "",
        hiRecBlue: "",
      },
      {
        srNo: "10",
        dateTable: "Mon, 16 Nov",
        opponentGrey: "@",
        imgUrl: tableImg9,
        opponentBlue: "Arizona",
        result: "2:35 AM",
        greenRedText: "",
        wL: "",
        hiPassBlue: "Tickets as low as $64",
        hiPassGrey: <RightLightArrow />,
        hiRushGrey: "",
        hiRushBlue: "",
        hiRecGrey: "",
        hiRecBlue: "",
      },
      {
        srNo: "11",
        dateTable: "BYE WEEK",
        opponentGrey: "",
        imgUrl: tableImg9,
        opponentBlue: "",
        result: "",
        greenRedText: "",
        wL: "",
        hiPassBlue: "",
        hiPassGrey: "",
        hiRushGrey: "",
        hiRushBlue: "",
        hiRecGrey: "",
        hiRecBlue: "",
      },
      {
        srNo: "12",
        dateTable: "Sun, 29 Nov",
        opponentGrey: "vs",
        imgUrl: tableImg10,
        opponentBlue: "Los Angeles",
        result: "11:30 PM",
        greenRedText: "",
        wL: "",
        hiPassBlue: "Tickets as low as $36",
        hiPassGrey: <RightLightArrow />,
        hiRushGrey: "",
        hiRushBlue: "",
        hiRecGrey: "",
        hiRecBlue: "",
      },
      {
        srNo: "13",
        dateTable: "Tue, 8 Dec",
        opponentGrey: "@",
        imgUrl: tableImg11,
        opponentBlue: "San Francisco",
        result: "6:45 AM",
        greenRedText: "",
        wL: "",
        hiPassBlue: "Tickets as low as $60",
        hiPassGrey: <RightLightArrow />,
        hiRushGrey: "",
        hiRushBlue: "",
        hiRecGrey: "",
        hiRecBlue: "",
      },
      {
        srNo: "14",
        dateTable: "Mon, 14 Dec",
        opponentGrey: "vs",
        imgUrl: tableImg12,
        opponentBlue: "Pittsburgh",
        result: "6:50 AM",
        greenRedText: "",
        wL: "",
        hiPassBlue: "Tickets as low as $71",
        hiPassGrey: <RightLightArrow />,
        hiRushGrey: "",
        hiRushBlue: "",
        hiRecGrey: "",
        hiRecBlue: "",
      },
      {
        srNo: "15",
        dateTable: "Sun, 20 Dec",
        opponentGrey: "@",
        imgUrl: tableImg13,
        opponentBlue: "Denver",
        result: "TBD",
        greenRedText: "",
        wL: "",
        hiPassBlue: "Tickets as low as $184",
        hiPassGrey: <RightLightArrow />,
        hiRushGrey: "",
        hiRushBlue: "",
        hiRecGrey: "",
        hiRecBlue: "",
      },
      {
        srNo: "16",
        dateTable: "Tue, 29 Dec",
        opponentGrey: "@",
        imgUrl: tableImg2,
        opponentBlue: "New England",
        result: "6:45 AM",
        greenRedText: "",
        wL: "",
        hiPassBlue: "Tickets as low as $160",
        hiPassGrey: <RightLightArrow />,
        hiRushGrey: "",
        hiRushBlue: "",
        hiRecGrey: "",
        hiRecBlue: "",
      },
      {
        srNo: "17",
        dateTable: "Sun, 3 Jan",
        opponentGrey: "vs",
        imgUrl: tableImg7,
        opponentBlue: "Miami",
        result: "11:30 PM",
        greenRedText: "",
        wL: "",
        hiPassBlue: "Tickets as low as $34  ",
        hiPassGrey: <RightLightArrow />,
        hiRushGrey: "",
        hiRushBlue: "",
        hiRecGrey: "",
        hiRecBlue: "",
      },
    ],
  },
  {
    heading: "Preseason",
    subHeading1: "WK",
    subHeading2: "DATE",
    subHeading3: "OPPONENT",
    subHeading4: "RESULT",
    subHeading5: "W-L",
    subHeading6: "HI PASS",
    subHeading7: "HI RUSH",
    subHeading8: "HI REC",
    tableContent: [
      {
        srNo: "18",
        dateTable: "Sat, 15 Aug",
        opponentGrey: "@",
        imgUrl: tableImg14,
        opponentBlue: "Baltimore",
        result: "",
        greenRedText: "",
        wL: "",
        hiPassBlue: "",
        hiPassGrey: "CANCELED",
        hiRushGrey: "",
        hiRushBlue: "",
        hiRecGrey: "",
        hiRecBlue: "",
      },
      {
        srNo: "19",
        dateTable: "Sat, 22 Aug",
        opponentGrey: "vs",
        imgUrl: tableImg15,
        opponentBlue: "Atlanta",
        result: "",
        greenRedText: "",
        wL: "",
        hiPassBlue: "",
        hiPassGrey: "CANCELED",
        hiRushGrey: "",
        hiRushBlue: "",
        hiRecGrey: "",
        hiRecBlue: "",
      },
      {
        srNo: "20",
        dateTable: "Sun, 30 Aug",
        opponentGrey: "vs",
        imgUrl: tableImg16,
        opponentBlue: "Indianapolis",
        result: "",
        greenRedText: "",
        wL: "",
        hiPassBlue: "",
        hiPassGrey: "CANCELED",
        hiRushGrey: "",
        hiRushBlue: "",
        hiRecGrey: "",
        hiRecBlue: "",
      },
      {
        srNo: "21",
        dateTable: "Fri, 4 Sep",
        opponentGrey: "vs",
        imgUrl: tableImg17,
        opponentBlue: "Detroit",
        result: "",
        greenRedText: "",
        wL: "",
        hiPassBlue: "",
        hiPassGrey: "CANCELED",
        hiRushGrey: "",
        hiRushBlue: "",
        hiRecGrey: "",
        hiRecBlue: "",
      },
    ],
  },
];
