import imagePath from "../../Assets/leader-img-3.png";
import imagePath2 from "../../Assets/fantasy-table-img-2.png";
import imagePath3 from "../../Assets/fantasy-table-img-3.png";
import imagePath4 from "../../Assets/fantasy-table-img-4.png";

export const fantasyFootballTableListMain = [
  {
    fantasyTableFixed: [
      {
        srNo: "1",
        imgUrl: imagePath,
        teamName: "Justin Herbert",
        teamDesc: "F • 39 - 29 vs. JAX",
      },
      {
        srNo: "2",
        imgUrl: imagePath2,
        teamName: "Justin Herbert",
        teamDesc: "F • 39 - 29 vs. JAX",
      },
      {
        srNo: "3",
        imgUrl: imagePath3,
        teamName: "Justin Herbert",
        teamDesc: "F • 39 - 29 vs. JAX",
      },
      {
        srNo: "4",
        imgUrl: imagePath4,
        teamName: "Justin Herbert",
        teamDesc: "F • 39 - 29 vs. JAX",
      },
      {
        srNo: "5",
        imgUrl: imagePath,
        teamName: "Justin Herbert",
        teamDesc: "F • 39 - 29 vs. JAX",
      },
      {
        srNo: "6",
        imgUrl: imagePath2,
        teamName: "Justin Herbert",
        teamDesc: "F • 39 - 29 vs. JAX",
      },
      {
        srNo: "7",
        imgUrl: imagePath3,
        teamName: "Justin Herbert",
        teamDesc: "F • 39 - 29 vs. JAX",
      },
      {
        srNo: "8",
        imgUrl: imagePath4,
        teamName: "Justin Herbert",
        teamDesc: "F • 39 - 29 vs. JAX",
      },
    ],
    fantasyFootballTableList: [
      {
        team: "LAC",
        pos: "7",
        wk: "QB",
        opp: "JAX",
        fptsG: "38.5",
        fpts: "38.48",
        yds1: "347",
        td1: "3",
        int: "0",
        yds2: "66",
        td2: "1",
        rec: "0",
        yds3: "0",
        td3: "0",
        tt: "0",
        ast: "0",
        td4: "0",
        sck: "0",
        int2: "0",
        ff: "0",
        fr: "0",
      },
      {
        team: "LAC",
        pos: "7",
        wk: "QB",
        opp: "JAX",
        fptsG: "38.5",
        fpts: "38.48",
        yds1: "347",
        td1: "3",
        int: "0",
        yds2: "66",
        td2: "1",
        rec: "0",
        yds3: "0",
        td3: "0",
        tt: "0",
        ast: "0",
        td4: "0",
        sck: "0",
        int2: "0",
        ff: "0",
        fr: "0",
      },
      {
        team: "LAC",
        pos: "7",
        wk: "QB",
        opp: "JAX",
        fptsG: "38.5",
        fpts: "38.48",
        yds1: "347",
        td1: "3",
        int: "0",
        yds2: "66",
        td2: "1",
        rec: "0",
        yds3: "0",
        td3: "0",
        tt: "0",
        ast: "0",
        td4: "0",
        sck: "0",
        int2: "0",
        ff: "0",
        fr: "0",
      },
      {
        team: "LAC",
        pos: "7",
        wk: "QB",
        opp: "JAX",
        fptsG: "38.5",
        fpts: "38.48",
        yds1: "347",
        td1: "3",
        int: "0",
        yds2: "66",
        td2: "1",
        rec: "0",
        yds3: "0",
        td3: "0",
        tt: "0",
        ast: "0",
        td4: "0",
        sck: "0",
        int2: "0",
        ff: "0",
        fr: "0",
      },
      {
        team: "LAC",
        pos: "7",
        wk: "QB",
        opp: "JAX",
        fptsG: "38.5",
        fpts: "38.48",
        yds1: "347",
        td1: "3",
        int: "0",
        yds2: "66",
        td2: "1",
        rec: "0",
        yds3: "0",
        td3: "0",
        tt: "0",
        ast: "0",
        td4: "0",
        sck: "0",
        int2: "0",
        ff: "0",
        fr: "0",
      },
      {
        team: "LAC",
        pos: "7",
        wk: "QB",
        opp: "JAX",
        fptsG: "38.5",
        fpts: "38.48",
        yds1: "347",
        td1: "3",
        int: "0",
        yds2: "66",
        td2: "1",
        rec: "0",
        yds3: "0",
        td3: "0",
        tt: "0",
        ast: "0",
        td4: "0",
        sck: "0",
        int2: "0",
        ff: "0",
        fr: "0",
      },
      {
        team: "LAC",
        pos: "7",
        wk: "QB",
        opp: "JAX",
        fptsG: "38.5",
        fpts: "38.48",
        yds1: "347",
        td1: "3",
        int: "0",
        yds2: "66",
        td2: "1",
        rec: "0",
        yds3: "0",
        td3: "0",
        tt: "0",
        ast: "0",
        td4: "0",
        sck: "0",
        int2: "0",
        ff: "0",
        fr: "0",
      },
      {
        team: "LAC",
        pos: "7",
        wk: "QB",
        opp: "JAX",
        fptsG: "38.5",
        fpts: "38.48",
        yds1: "347",
        td1: "3",
        int: "0",
        yds2: "66",
        td2: "1",
        rec: "0",
        yds3: "0",
        td3: "0",
        tt: "0",
        ast: "0",
        td4: "0",
        sck: "0",
        int2: "0",
        ff: "0",
        fr: "0",
      },
    ],
  },
];
